# Generated by Django 3.2 on 2021-05-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_person',
            name='birth_date',
            field=models.DateField(max_length=30),
        ),
    ]
