# Generated by Django 3.1.1 on 2021-05-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transaction', '0002_alter_office_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_person',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taxperiodtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taxsetup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
