# Generated by Django 3.2 on 2021-05-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transaction', '0004_auto_20210505_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='cashout_amt',
            field=models.FloatField(default=0),
        ),
    ]
