# Generated by Django 3.2 on 2021-05-06 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_transaction', '0005_tax_cashout_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tax_usr', to='auth.user'),
            preserve_default=False,
        ),
    ]
