# Generated by Django 3.2 on 2021-04-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
