# Generated by Django 3.2 on 2021-04-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=100),
        ),
    ]
