# Generated by Django 3.1.1 on 2021-05-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0034_auto_20210505_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=100),
        ),
    ]
