# Generated by Django 3.2 on 2021-04-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_amnt', models.FloatField()),
                ('ref_amnt', models.FloatField()),
                ('prantic_amnt', models.FloatField()),
                ('middle_amnt', models.FloatField()),
                ('ehp_amnt', models.FloatField()),
                ('incentive_amnt', models.FloatField()),
            ],
        ),
    ]
