# Generated by Django 3.2 on 2021-04-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='esp_amnt',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
