# Generated by Django 3.2 on 2021-04-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0003_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_amnt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
