# Generated by Django 3.2 on 2021-04-30 05:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0004_account_total_amnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='total_amnt',
        ),
        migrations.AddField(
            model_name='account',
            name='total_amnt_WoP',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_amnt', models.FloatField()),
                ('current_amnt', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_cashout_amnt', models.FloatField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_balance.account')),
            ],
        ),
    ]
