# Generated by Django 3.2 on 2021-04-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0006_totalamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalamount',
            name='adjast_amnt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalamount',
            name='current_amnt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalamount',
            name='previous_amnt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalamount',
            name='requisation_amnt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
