# Generated by Django 3.2 on 2021-04-30 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_balance', '0007_auto_20210430_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='adjast_amnt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='requisation_amnt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='current_amnt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='prev_amnt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='totalamount',
        ),
    ]
