# Generated by Django 3.2 on 2021-04-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0008_auto_20210430_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
