# Generated by Django 3.2 on 2021-04-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0009_alter_withdraw_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='adjast_amnt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='current_amnt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='prev_amnt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='requisation_amnt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='total_cashout_amnt',
            field=models.FloatField(default=0),
        ),
    ]
