# Generated by Django 3.2 on 2021-04-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0010_auto_20210430_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='modified_at',
            field=models.DateTimeField(),
        ),
    ]
