# Generated by Django 3.2 on 2021-05-01 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0011_auto_20210430_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
