# Generated by Django 3.2 on 2021-05-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0013_auto_20210501_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='modified_at',
            field=models.DateTimeField(verbose_name='modified date'),
        ),
    ]
