# Generated by Django 3.2 on 2021-05-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0017_tax_taxdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxdetails',
            old_name='tax_amount',
            new_name='tax_amount_tot',
        ),
        migrations.AddField(
            model_name='taxdetails',
            name='tax_curr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='taxdetails',
            name='tax_prev',
            field=models.FloatField(default=0),
        ),
    ]
