# Generated by Django 3.2 on 2021-05-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0019_alter_taxdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdetails',
            name='withdra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account_balance.withdraw'),
            preserve_default=False,
        ),
    ]
