# Generated by Django 3.2 on 2021-05-02 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_balance', '0021_delete_taxdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='taxDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_prev', models.FloatField(default=0)),
                ('tax_curr', models.FloatField(default=0)),
                ('tax_amount_tot', models.FloatField(default=0)),
                ('tax_id', models.CharField(max_length=100)),
                ('tax_pay_date', models.DateTimeField(auto_now=True)),
                ('tax_info_law', models.CharField(blank=True, max_length=155, null=True)),
                ('tax_given_area', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_description', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('withdra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_balance.withdraw')),
            ],
        ),
    ]
