# Generated by Django 3.1.1 on 2021-05-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0023_auto_20210505_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ehp_amnt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='esp_amnt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='incentive_amnt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='middle_amnt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='prantic_amnt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='purchase_amnt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='ref_amnt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_amnt_WoP',
            field=models.FloatField(default=0),
        ),
    ]
